import typing

from django.utils.translation import gettext_lazy as _

GENDER_MALE = "male"
GENDER_FEMALE = "female"

GENDER_CHOICES = (
    (GENDER_MALE, _('Male')),
    (GENDER_FEMALE, _('Female')),
)

LIFESTYLE_SEDENTARY = "sedentary"
LIFESTYLE_SLIGHTLY_ACTIVE = "slightly_active"
LIFESTYLE_MODERATELY_ACTIVE = "moderately_active"
LIFESTYLE_VERY_ACTIVE = "very_active"
LIFESTYLE_EXTREMELY_ACTIVE = "extremely_active"

LIFESTYLE_CHOICES = (
    (LIFESTYLE_SEDENTARY, _('Sedentary (desk job; little or no exercise)')),
    (LIFESTYLE_SLIGHTLY_ACTIVE, _('Slightly Active (exercise 1-3 times a week)')),
    (LIFESTYLE_MODERATELY_ACTIVE, _('Moderately Active (exercise 3-5 times a week)')),
    (LIFESTYLE_VERY_ACTIVE, _('Very Active (exercise 6-7 times a week)')),
    (LIFESTYLE_EXTREMELY_ACTIVE, _('Extremely Active (physical job or regular training)')),
)

GOAL_MAINTENANCE = 'maintenance'
GOAL_MUSCLE_GAIN = 'muscle_gain'
GOAL_FAT_LOSS = 'fat_loss'

GOAL_CHOICES = (
    (GOAL_MAINTENANCE, _('Maintenance (maintaining current weight)')),
    (GOAL_MUSCLE_GAIN, _('Muscle Gain (building muscle mass)')),
    (GOAL_FAT_LOSS, _('Fat Loss (losing body fat)')),
)

NUTRITIONAL_ITEM_CALORIES = "calories"
NUTRITIONAL_ITEM_PROTEIN = "protein"
NUTRITIONAL_ITEM_FAT = "fat"
NUTRITIONAL_ITEM_CHOLESTEROL = "cholesterol"
NUTRITIONAL_ITEM_CARBOHYDRATE = "carbohydrate"
NUTRITIONAL_ITEM_SUGAR = "sugar"
NUTRITIONAL_ITEM_SODIUM = "sodium"
NUTRITIONAL_ITEM_CALCIUM = "calcium"
NUTRITIONAL_ITEM_IRON = "iron"
NUTRITIONAL_ITEM_POTASSIUM = "potassium"
NUTRITIONAL_ITEM_VITAMIN_C = "vitamin_c"

NUTRITIONAL_ITEMS = [
    NUTRITIONAL_ITEM_CALORIES,
    NUTRITIONAL_ITEM_PROTEIN,
    NUTRITIONAL_ITEM_FAT,
    NUTRITIONAL_ITEM_CHOLESTEROL,
    NUTRITIONAL_ITEM_CARBOHYDRATE,
    NUTRITIONAL_ITEM_SUGAR,
    NUTRITIONAL_ITEM_SODIUM,
    NUTRITIONAL_ITEM_CALCIUM,
    NUTRITIONAL_ITEM_IRON,
    NUTRITIONAL_ITEM_POTASSIUM,
    NUTRITIONAL_ITEM_VITAMIN_C,
]

NUTRITIONAL_ITEM_NAME_MAPPING = {
    NUTRITIONAL_ITEM_CALORIES: "Calories",
    NUTRITIONAL_ITEM_PROTEIN: "Protein",
    NUTRITIONAL_ITEM_FAT: "Fat",
    NUTRITIONAL_ITEM_CHOLESTEROL: "Cholesterol",
    NUTRITIONAL_ITEM_CARBOHYDRATE: "Carbohydrate",
    NUTRITIONAL_ITEM_SUGAR: "Sugar",
    NUTRITIONAL_ITEM_SODIUM: "Sodium",
    NUTRITIONAL_ITEM_CALCIUM: "Calcium",
    NUTRITIONAL_ITEM_IRON: "Iron",
    NUTRITIONAL_ITEM_POTASSIUM: "Potassium",
    NUTRITIONAL_ITEM_VITAMIN_C: "Vitamin C",
}

NUTRITIONAL_ITEM_ID_MAPPING = {
    NUTRITIONAL_ITEM_CALORIES: 1008,
    NUTRITIONAL_ITEM_PROTEIN: 1003,
    NUTRITIONAL_ITEM_FAT: 1004,
    NUTRITIONAL_ITEM_CHOLESTEROL: 1253,
    NUTRITIONAL_ITEM_CARBOHYDRATE: 1005,
    NUTRITIONAL_ITEM_SUGAR: 2000,
    NUTRITIONAL_ITEM_SODIUM: 1093,
    NUTRITIONAL_ITEM_CALCIUM: 1087,
    NUTRITIONAL_ITEM_IRON: 1089,
    NUTRITIONAL_ITEM_POTASSIUM: 1092,
    NUTRITIONAL_ITEM_VITAMIN_C: 1162,
}

NUTRITIONAL_ITEM_UNIT_MAPPING = {
    NUTRITIONAL_ITEM_CALORIES: "kcal",
    NUTRITIONAL_ITEM_PROTEIN: "grams",
    NUTRITIONAL_ITEM_FAT: "grams",
    NUTRITIONAL_ITEM_CHOLESTEROL: "milligrams",
    NUTRITIONAL_ITEM_CARBOHYDRATE: "grams",
    NUTRITIONAL_ITEM_SUGAR: "grams",
    NUTRITIONAL_ITEM_SODIUM: "milligrams",
    NUTRITIONAL_ITEM_CALCIUM: "milligrams",
    NUTRITIONAL_ITEM_IRON: "milligrams",
    NUTRITIONAL_ITEM_POTASSIUM: "milligrams",
    NUTRITIONAL_ITEM_VITAMIN_C: "milligrams",
}

MEAL_BREAKFAST = "breakfast"
MEAL_MORNING_SNACK = "morning_snack"
MEAL_LUNCH = "lunch"
MEAL_AFTERNOON_SNACK = "afternoon_snack"
MEAL_DINNER = "dinner"

MEALS = [
    MEAL_BREAKFAST,
    MEAL_MORNING_SNACK,
    MEAL_LUNCH,
    MEAL_AFTERNOON_SNACK,
    MEAL_DINNER,
]

MEAL_NAME_MAPPING = {
    MEAL_BREAKFAST: "Breakfast",
    MEAL_MORNING_SNACK: "Morning Snack",
    MEAL_LUNCH: "Lunch",
    MEAL_AFTERNOON_SNACK: "Afternoon Snack",
    MEAL_DINNER: "Dinner",
}

MEAL_VAR_MAPPING = {
    MEAL_BREAKFAST: "b",
    MEAL_MORNING_SNACK: "m",
    MEAL_LUNCH: "l",
    MEAL_AFTERNOON_SNACK: "a",
    MEAL_DINNER: "d",
}

FOOD_CATEGORY_DAIRY_AND_EGG_PRODUCTS = "dairy_and_egg_products"
FOOD_CATEGORY_SPICES_AND_HERBS = "spices_and_herbs"
FOOD_CATEGORY_BABY_FOODS = "baby_foods"
FOOD_CATEGORY_FATS_AND_OILS = "fats_and_oils"
FOOD_CATEGORY_POULTRY_PRODUCTS = "poultry_products"
FOOD_CATEGORY_SOUPS_SAUCES_AND_GRAVIES = "soups_sauces_and_gravies"
FOOD_CATEGORY_SAUSAGES_AND_LUNCHEON_MEATS = "sausages_and_luncheon_meats"
FOOD_CATEGORY_BREAKFAST_CEREALS = "breakfast_cereals"
FOOD_CATEGORY_FRUITS_AND_FRUIT_JUICES = "fruits_and_fruit_juices"
FOOD_CATEGORY_PORK_PRODUCTS = "pork_products"
FOOD_CATEGORY_VEGETABLES_AND_VEGETABLE_PRODUCTS = "vegetables_and_vegetable_products"
FOOD_CATEGORY_NUT_AND_SEED_PRODUCTS = "nut_and_seed_products"
FOOD_CATEGORY_BEEF_PRODUCTS = "beef_products"
FOOD_CATEGORY_BEVERAGES = "beverages"
FOOD_CATEGORY_FINFISH_AND_SHELLFISH_PRODUCTS = "finfish_and_shellfish_products"
FOOD_CATEGORY_LEGUMES_AND_LEGUME_PRODUCTS = "legumes_and_legume_products"
FOOD_CATEGORY_LAMB_VEAL_AND_GAME_PRODUCTS = "lamb_veal_and_game_products"
FOOD_CATEGORY_BAKED_PRODUCTS = "baked_products"
FOOD_CATEGORY_SWEETS = "sweets"
FOOD_CATEGORY_CEREAL_GRAINS_AND_PASTA = "cereal_grains_and_pasta"
FOOD_CATEGORY_FAST_FOODS = "fast_foods"
FOOD_CATEGORY_MEALS_ENTREES_AND_SIDE_DISHES = "meals_entrees_and_side_dishes"
FOOD_CATEGORY_SNACKS = "snacks"
FOOD_CATEGORY_AMERICAN_INDIAN_ALASKA_NATIVE_FOODS = "american_indian_alaska_native_foods"
FOOD_CATEGORY_RESTAURANT_FOODS = "restaurant_foods"

FOOD_CATEGORY_ID_MAPPING = {
    FOOD_CATEGORY_DAIRY_AND_EGG_PRODUCTS: 1,
    FOOD_CATEGORY_SPICES_AND_HERBS: 2,
    FOOD_CATEGORY_BABY_FOODS: 3,
    FOOD_CATEGORY_FATS_AND_OILS: 4,
    FOOD_CATEGORY_POULTRY_PRODUCTS: 5,
    FOOD_CATEGORY_SOUPS_SAUCES_AND_GRAVIES: 6,
    FOOD_CATEGORY_SAUSAGES_AND_LUNCHEON_MEATS: 7,
    FOOD_CATEGORY_BREAKFAST_CEREALS: 8,
    FOOD_CATEGORY_FRUITS_AND_FRUIT_JUICES: 9,
    FOOD_CATEGORY_PORK_PRODUCTS: 10,
    FOOD_CATEGORY_VEGETABLES_AND_VEGETABLE_PRODUCTS: 11,
    FOOD_CATEGORY_NUT_AND_SEED_PRODUCTS: 12,
    FOOD_CATEGORY_BEEF_PRODUCTS: 13,
    FOOD_CATEGORY_BEVERAGES: 14,
    FOOD_CATEGORY_FINFISH_AND_SHELLFISH_PRODUCTS: 15,
    FOOD_CATEGORY_LEGUMES_AND_LEGUME_PRODUCTS: 16,
    FOOD_CATEGORY_LAMB_VEAL_AND_GAME_PRODUCTS: 17,
    FOOD_CATEGORY_BAKED_PRODUCTS: 18,
    FOOD_CATEGORY_SWEETS: 19,
    FOOD_CATEGORY_CEREAL_GRAINS_AND_PASTA: 20,
    FOOD_CATEGORY_FAST_FOODS: 21,
    FOOD_CATEGORY_MEALS_ENTREES_AND_SIDE_DISHES: 22,
    FOOD_CATEGORY_SNACKS: 23,
    FOOD_CATEGORY_AMERICAN_INDIAN_ALASKA_NATIVE_FOODS: 24,
    FOOD_CATEGORY_RESTAURANT_FOODS: 25,
}

MEAL_FOOD_CATEGORY_MAPPING: typing.Dict[str, set] = {
    MEAL_BREAKFAST: {
        FOOD_CATEGORY_DAIRY_AND_EGG_PRODUCTS,
        FOOD_CATEGORY_SAUSAGES_AND_LUNCHEON_MEATS,
        FOOD_CATEGORY_BREAKFAST_CEREALS,
        FOOD_CATEGORY_FRUITS_AND_FRUIT_JUICES,
        FOOD_CATEGORY_VEGETABLES_AND_VEGETABLE_PRODUCTS,
        FOOD_CATEGORY_NUT_AND_SEED_PRODUCTS,
        FOOD_CATEGORY_BEVERAGES,
        FOOD_CATEGORY_LEGUMES_AND_LEGUME_PRODUCTS,
        FOOD_CATEGORY_BAKED_PRODUCTS,
    },
    MEAL_MORNING_SNACK: {
        FOOD_CATEGORY_SAUSAGES_AND_LUNCHEON_MEATS,
        FOOD_CATEGORY_FRUITS_AND_FRUIT_JUICES,
        FOOD_CATEGORY_VEGETABLES_AND_VEGETABLE_PRODUCTS,
        FOOD_CATEGORY_NUT_AND_SEED_PRODUCTS,
        FOOD_CATEGORY_BEVERAGES,
        FOOD_CATEGORY_LEGUMES_AND_LEGUME_PRODUCTS,
        FOOD_CATEGORY_BAKED_PRODUCTS,
        FOOD_CATEGORY_SNACKS,
    },
    MEAL_LUNCH: {
        FOOD_CATEGORY_POULTRY_PRODUCTS,
        FOOD_CATEGORY_SOUPS_SAUCES_AND_GRAVIES,
        FOOD_CATEGORY_SAUSAGES_AND_LUNCHEON_MEATS,
        FOOD_CATEGORY_FRUITS_AND_FRUIT_JUICES,
        FOOD_CATEGORY_VEGETABLES_AND_VEGETABLE_PRODUCTS,
        FOOD_CATEGORY_NUT_AND_SEED_PRODUCTS,
        FOOD_CATEGORY_BEEF_PRODUCTS,
        FOOD_CATEGORY_BEVERAGES,
        FOOD_CATEGORY_FINFISH_AND_SHELLFISH_PRODUCTS,
        FOOD_CATEGORY_LEGUMES_AND_LEGUME_PRODUCTS,
        FOOD_CATEGORY_LAMB_VEAL_AND_GAME_PRODUCTS,
        FOOD_CATEGORY_BAKED_PRODUCTS,
        FOOD_CATEGORY_CEREAL_GRAINS_AND_PASTA,
        FOOD_CATEGORY_FAST_FOODS,
        FOOD_CATEGORY_RESTAURANT_FOODS,
    },
    MEAL_AFTERNOON_SNACK: {
        FOOD_CATEGORY_SOUPS_SAUCES_AND_GRAVIES,
        FOOD_CATEGORY_SAUSAGES_AND_LUNCHEON_MEATS,
        FOOD_CATEGORY_FRUITS_AND_FRUIT_JUICES,
        FOOD_CATEGORY_VEGETABLES_AND_VEGETABLE_PRODUCTS,
        FOOD_CATEGORY_NUT_AND_SEED_PRODUCTS,
        FOOD_CATEGORY_BEVERAGES,
        FOOD_CATEGORY_LEGUMES_AND_LEGUME_PRODUCTS,
        FOOD_CATEGORY_BAKED_PRODUCTS,
        FOOD_CATEGORY_SNACKS,
    },
    MEAL_DINNER: {
        FOOD_CATEGORY_POULTRY_PRODUCTS,
        FOOD_CATEGORY_SOUPS_SAUCES_AND_GRAVIES,
        FOOD_CATEGORY_SAUSAGES_AND_LUNCHEON_MEATS,
        FOOD_CATEGORY_FRUITS_AND_FRUIT_JUICES,
        FOOD_CATEGORY_VEGETABLES_AND_VEGETABLE_PRODUCTS,
        FOOD_CATEGORY_NUT_AND_SEED_PRODUCTS,
        FOOD_CATEGORY_BEEF_PRODUCTS,
        FOOD_CATEGORY_BEVERAGES,
        FOOD_CATEGORY_FINFISH_AND_SHELLFISH_PRODUCTS,
        FOOD_CATEGORY_LEGUMES_AND_LEGUME_PRODUCTS,
        FOOD_CATEGORY_LAMB_VEAL_AND_GAME_PRODUCTS,
        FOOD_CATEGORY_BAKED_PRODUCTS,
        FOOD_CATEGORY_CEREAL_GRAINS_AND_PASTA,
        FOOD_CATEGORY_FAST_FOODS,
        FOOD_CATEGORY_RESTAURANT_FOODS,
    },
}

COLUMN_FDC_ID = "fdc_id"
COLUMN_NUTRIENT_ID = "nutrient_id"
COLUMN_FOOD_CATEGORY_ID = "food_category_id"
COLUMN_DESCRIPTION = "description"
COLUMN_AMOUNT = "amount"

COLUMN_IS_BREAKFAST = "is_breakfast"
COLUMN_IS_MORNING_SNACK = "is_morning_snack"
COLUMN_IS_LUNCH = "is_lunch"
COLUMN_IS_AFTERNOON_SNACK = "is_afternoon_snack"
COLUMN_IS_DINNER = "is_dinner"
COLUMN_IS_BEVERAGE = "is_beverage"

COLUMN_CALORIES = "calories"
COLUMN_PROTEIN = "protein"
COLUMN_FAT = "fat"
COLUMN_CHOLESTEROL = "cholesterol"
COLUMN_CARBOHYDRATE = "carbohydrate"
COLUMN_SUGAR = "sugar"
COLUMN_SODIUM = "sodium"
COLUMN_CALCIUM = "calcium"
COLUMN_IRON = "iron"
COLUMN_POTASSIUM = "potassium"
COLUMN_VITAMIN_C = "vitamin_c"

MIN_MEAL_FOOD = 200
MAX_MEAL_FOOD = 800

MIN_SNACK_FOOD = 100
MAX_SNACK_FOOD = 700

MIN_MEAL_BEVERAGE = 240
MAX_MEAL_BEVERAGE = 360

MIN_SNACK_BEVERAGE = 240
MAX_SNACK_BEVERAGE = 360

MIN_FOOD = 50
MAX_FOOD = 500


def category_id_mapper(cat):
    return FOOD_CATEGORY_ID_MAPPING[cat]
